# Site settings
title: FotoBox für Darmstadt, Mannheim, Frankfurt und Umgebung
locale: de_DE
email: info@fotos-aus-der-box.de
telefon: +49 6258 903570 oder +49 163 8493889
description: "Mieten Sie die FotoBox für Darmstadt, Groß-Umstadt, Mannheim, Frankfurt, Gernsheim und Umgebung mit unbegrenzter Bilderanzahl, online Galerie, Studiobeleuchtung und Betreuung vor Ort." # this means to ignore newlines until "baseurl:"
keywords: "FotoBox, PhotoBooth, Fotoautomat, FotoKiosk, Fotos drucken, Geburtstag, Jubiläum, Hochzeit, Event, Messe, Darmstadt, Gernsheim, Groß-Umstadt, Biebesheim, Mannheim, Frankfurt, Lorsch"
# baseurl: "/fotoboxo" # the subpath of your site, e.g. /blog/
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.fotos-aus-der-box.de" # the base hostname & protocol for your site
#url: "http://localhost:4000" # the base hostname & protocol for your site
#url: "" # the base hostname & protocol for your site
#url_cdn: https://cloudfront.fotos-aus-der-box.de
url_cdn: //d2pgtqatw1ohn4.cloudfront.net
version: ".5"
#permalink:    /:year/:month/:day/:title.html

twitter_username:
github_username:

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-redirect-from

assets:
  css: "/assets/css"
  fonts: "/assets/fonts"
  images: "/assets/images"
  js: "/assets/js"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages" 
    values:
      layout: "page" # overrides previous default layout
 
# Site owner
owner:
  name: Thomas Wetterer
  avatar: thomas-wetterer.jpg
  email: thomas@wetterer.de
  disqus-shortname: wetty
  twitter: twettyr #username
  facebook: #username
  github: wetty #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: wetterer #username
  tumblr: #username
  500px: wetty
  xing:
  bing-verify: EE0D978C30EE22199D09EFD26CB45F0B
  google:
    plus: ThomasWetterer #username
    analytics: UA-2881242-4
    verify: uWUlAKKMSFqda-kxKIfgqE5PkEIFqqVyMfj9emXPp7Q
    ad-client: ca-pub-7756413429414204
    ad-slot: 1775973063


# Reading Files
include:
  - .htaccess
  - _pages
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
