# Site settings
title: FotoBox für Gernsheim und Umgebung
locale: de_DE
email: info@fotos-aus-der-box.de
telefon: +49 6258 903570
description: "Mieten Sie die FotoBox für Gernsheim, Darmstadt und Umgebung mit unbegrenzter Bilderanzahl, online Gallerie und Studiobeleuchtung inklusive Betreuung vor Ort." # this means to ignore newlines until "baseurl:"
keywords: "FotoBox, PhotoBooth, Fotoautomat, Geburtstag, Jubiläum, Hochzeit, Event, Messe, Gernsheim, Darmstadt, Groß-Umstadt, Biebesheim"
# baseurl: "/fotoboxo" # the subpath of your site, e.g. /blog/
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.fotos-aus-der-box.de" # the base hostname & protocol for your site
#url: "http://localhost:4000" # the base hostname & protocol for your site
#url: "" # the base hostname & protocol for your site
url_cdn: http://cloudfront.fotos-aus-der-box.de
version: ".1"

twitter_username:
github_username:

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

assets:
  css: "/assets/css"
  fonts: "/assets/fonts"
  images: "/assets/images"
  js: "/assets/js"

# Site owner
owner:
  name: Thomas Wetterer
  avatar: thomas-wetterer.jpg
  email: thomas@wetterer.de
  disqus-shortname: wetty
  twitter: twettyr #username
  facebook: #username
  github: wetty #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: wetterer #username
  tumblr: #username
  500px: wetty
  xing:
  bing-verify: EE0D978C30EE22199D09EFD26CB45F0B
  google:
    plus: ThomasWetterer #username
    verify: uWUlAKKMSFqda-kxKIfgqE5PkEIFqqVyMfj9emXPp7Q

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
